### PR TITLE
Fix ioctl() call compilation error for freebsd

### LINKED ISSUE #12: Can't compile on FreeBSD 11.0 - mismatched types at ioctl() call
**Problem description**
Compilation fails at line 398 or src/unix/terminal.rs [1]:
`let res = unsafe { ioctl(fd, TIOCGWINSZ, &mut winsz) };`
with error:
```
398:34: 398:44 note: expected type u64
398:34: 398:44 note:    found type `u32`
error: aborting due to previous error
error: Could not compile `linefeed`.
```

**Reason**
The problem is that in rust libc for the platform x86_64-unknown-freebsd, TIOCGWINSZ is u32 and not u64 [2], while `ioctl` accepts u64 as a second argument [3].

I believe this is specific to freebsd. For example, in the case of x86_64-unknown-linux-gnu, TIOCGWINSZ is u64 [4].

**Fix**
It may be enough to cast TIOCGWINSZ to u64.

However, I'm not sure whether this has other effects (e.g., maybe for some architectures ioctl accepts u32?).

**Edit**
The fix I suggested **would not work** on the following architectures:
`x86_64-unknown-linux-musl, arm-linux-androideabi, asmjs-unknown-emscripten, wasm32-unknown-emscripten`,
where `ioctl()` accepts as a second parameter a u32 [5].

However, on those platforms TIOCGWINSZ is of type c_int, which means compilation of linefeed should succeed for them.

This means that the discrepancy (i.e., TIOCGWINSZ is u32 [2] but the second parameter of ioctl() is u64 [6]) only happens for freebsd.
Does this mean the problem should be fixed in rust libc?

[1] https://github.com/murarth/linefeed/blob/master/src/unix/terminal.rs#L398
[2] https://doc.rust-lang.org/libc/x86_64-unknown-freebsd/libc/constant.TIOCGWINSZ.html
[3] https://doc.rust-lang.org/libc/x86_64-unknown-freebsd/libc/fn.ioctl.html
[4] https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/constant.TIOCGWINSZ.html
[5] https://doc.rust-lang.org/libc/
[6] https://doc.rust-lang.org/libc/x86_64-unknown-freebsd/libc/fn.ioctl.html

### PR DESCRIPTION
**Pull request by gchers**
This is a temporary fix to https://github.com/rust-lang/libc/pull/704 and fixes #12.

May want to remove when rust libc accepts https://github.com/rust-lang/libc/pull/704.

### CODE REVIEW

File: src/unix/terminal.rs [hunk 1]
```diff
@@ -395,8 +395,14 @@ struct Winsize {
 fn get_winsize(fd: c_int) -> io::Result<Winsize> {
     let mut winsz: Winsize = unsafe { zeroed() };
 
+    #[cfg(not(target_os = "freebsd"))]
     let res = unsafe { ioctl(fd, TIOCGWINSZ, &mut winsz) };
 
+    // NOTE: this is a temporary fix to a libc bug described in:
+    //  https://github.com/rust-lang/libc/pull/704
+    #[cfg(target_os = "freebsd")]
+    let res = unsafe { ioctl(fd, TIOCGWINSZ as u64, &mut winsz) };
```
Comment (murarth) [inline src/unix/terminal.rs]: A couple minor points: I believe attributes on expressions landed in stable rustc only a few days ago, so I think it would be better to implement this as `cfg`-marked functions, to continue supporting the old stable. Also, I think the cast would be better done as `as c_ulong`.

**Comment by gchers** [comment]
Hi, this should solve with backward compatibility.

NOTE_1: I wasn't sure how to create a more generic ioctl() wrapper (i.e., one that could accept either c_int or c_ulong for argument *request*, which is the case for non-freebsd platforms), so I simply created a wrapper for the call to ioctl() with request=TIOCGWINSZ.

NOTE_2:
Just in case, I post here for reference, in order:
```platform, TIOCGWINSZ type, ioctl() request type```
for the current libc, and mark with * the wrong entries.
I omit openbsd -like entries for which TIOCGWINSZ is not defined; I suspect linefeed doesn't support them anyway.

```
linux:
mips-unknown-linux-gnu, c_ulong, c_ulong
arm-unknown-linux-gnueabihf, c_ulong, c_ulong
i686-unknown-linux-gnu, c_ulong, c_ulong
x86_64-unknown-linux-gnu, c_ulong, c_ulong
aarch64-unknown-linux-gnu, c_ulong, c_ulong
x86_64-unknown-linux-musl, c_int, c_int

linux-android:
arm-linux-androideabi, c_int, c_int

freebsd:
* x86_64-unknown-freebsd, c_uint, c_ulong
* x86_64-unknown-dragonfly, c_uint, c_ulong

apple:
x86_64-apple-darwin, c_ulong, c_ulong
i686-apple-darwin, c_ulong, c_ulong

other:
asmjs-unknown-emscripten, c_int, c_int
wasm32-unknown-emscripten, c_int, c_int
sparc64-unknown-linux-gnu, c_ulong, c_ulong
```

File: src/unix/terminal.rs [hunk 2]
```diff
@@ -6,7 +6,7 @@ use std::sync::atomic::{AtomicUsize, ATOMIC_USIZE_INIT, Ordering};
 use std::time::Duration;
 
 use libc::{
-    c_int, c_ushort, c_void,
+    c_int, c_ushort, c_ulong, c_void,
```
Comment (murarth) [inline src/unix/terminal.rs]: This generates an `unused_imports` warning on non-freebsd platforms. You can instead add `use libc::c_ulong;` inside the freebsd version of `ioctl_wrapper`.

**Comment by murarth** [comment]
If dragonfly has the same issue, you can go ahead and apply this fix for dragonfly, as well.

I'd like to support any platform that can reasonably be supported. Do you know whether it is a bug that `libc` doesn't define `TIOCGWINSZ` for OpenBSD or does OpenBSD truly not implement this ioctl request?

**Comment by murarth** [comment]
I've just realized something that will greatly simplify the implementation of this fix: For each integer type in Rust, there exist `From` implementations to convert losslessly from each smaller integer type of the same signedness, e.g. from `u32` to `u64`. So, the only change that needs to be made to the original code is to pass `TIOCGWINSZ.into()` to `ioctl`. (Though you can preserve the comment about the FreeBSD/Dragonfly issue that explains why this is necessary.)

Because a `From` implementation also exists to convert a value of any type into itself, `TIOCGWINSZ.into()` can be used on all platforms (provided that the signedness matches for the type of the constant `TIOCGWINSZ` and the type expected by `ioctl`, which does appear to be the case).

**Comment by gchers** [comment]
Such an elegant solution! Sweet, I was really hoping there was something like that.

As for your openbsd question. TIOCGWINSZ is defined, but not in rust libc [1].
I'll: i) try compiling linefeed on an openbsd tomorrow (which I suspect will fail), ii) look for its actual value in ioctl.h (it may be different from the one in freebsd).

[1] https://man.openbsd.org/tty.4#TIOCGWINSZ

**Comment by murarth** [comment]
Looks good. Go ahead and squash the commits and I'll merge it.
