### ISSUE TITLE
build failure on rustc 1.21

### ISSUE THREAD

**Issue by ericseppanen** [murarth/linefeed#26]
Since commit bb867da4f I am unable to build on Ubuntu 17.10 w/ rustc 1.21:

```
error[E0277]: the trait bound `std::option::Option<inputrc::Token<'_>>: std::ops::Try` is not satisfied
   --> src/inputrc.rs:189:21
    |
189 |         let start = tokens.next()?;
    |                     --------------
    |                     |
    |                     the `?` operator can only be used in a function that returns `Result` (or another type that implements `std::ops::Try`)
    |                     in this macro invocation
    |
    = help: the trait `std::ops::Try` is not implemented for `std::option::Option<inputrc::Token<'_>>`
    = note: required by `std::ops::Try::into_result`
```

The same error repeats in many more locations.

**Comment by murarth** [comment]
The Rust programming language moves pretty fast, at least compared to some committee-driven languages. Rust 1.21 was released in October of last year and did not yet support using the `?` operator with `Option<T>` values.

If you've installed Rust from the Ubuntu APT repositories, it's going to give you an older version. For this reason, the preferred installation method is to use rustup. The official Rust website has more information about how to use it and how it works: https://www.rust-lang.org/install.html

Once you're using rustup (or if you already are), you can run `rustup update stable` to get the latest version. A new version is released every six weeks.
